### ISSUE TITLE
Retriving/pushing global data

### ISSUE THREAD

**Issue by zjwegert** [gridap/GridapDistributed.jl#106]
Hi all,
GridapDistributed looks like a great package. I'm interested in integrating it into my existing code-base for level set-based topology optimisation. To do so (easily), I need to be able to retrieve `free_values` and `cell_dof_values` over the whole mesh (as in `Gridap`) and also be able to push like data from the global mesh to the parts.

Is this type of operation currently possible in GridapDistributed?

**Comment by JordiManyer** [comment]
Hi, 

- To retrieve `free_values` from a FEFunction, use `get_free_dof_values`, found [here](https://github.com/gridap/GridapDistributed.jl/blob/843de3d2ab4f21d076a81c91a1d17247023e23db/src/FESpaces.jl#L257).
- To retrieve `dirichlet_values` from a FESpace, use `get_dirichlet_dof_values`, found [here](https://github.com/gridap/GridapDistributed.jl/blob/843de3d2ab4f21d076a81c91a1d17247023e23db/src/FESpaces.jl#L288).

You will then have `fv=free_values` as a `PVector` and `dv=dirichlet_values` as a `AbstractPData{<:Vector}`. To scatter them into `cell_values` for a `DistributedSingleFieldFESpace`, `Uh`, you can do something like this: 

```julia
map_parts(scatter_free_and_dirichlet_values,local_views(Uh),local_views(fv),dv)
```

Note that `local_views` is not necessary for the `dirichlet_values` since it is already an `AbstractPData`. This is local, so make sure the `free_values` contain also the ghost dofs. If not, you can communicate the dofs by calling `exchange!(free_values)`.

To do the opposite conversion, i.e from cell values to vectors, you can use `gather_free_values!/gather_free_and_dirichlet_values!` found [here](https://github.com/gridap/GridapDistributed.jl/blob/843de3d2ab4f21d076a81c91a1d17247023e23db/src/FESpaces.jl#L48). 

There are also functions that reproduce these two functionalities for subsections of the mesh. You can look into [this](https://github.com/gridap/GridapDistributed.jl/blob/843de3d2ab4f21d076a81c91a1d17247023e23db/src/FESpaces.jl#L52) and [this](https://github.com/gridap/GridapDistributed.jl/blob/843de3d2ab4f21d076a81c91a1d17247023e23db/src/FESpaces.jl#L74). 

Let me know if you need anything else.

**Comment by zjwegert** [comment]
Hi @JordiManyer,
Thanks for the detailed response. I might not of been clear before though.. Although,
```
fv = get_free_dof_values(uh)
dv = get_dirichlet_dof_values(U)
map_parts(scatter_free_and_dirichlet_values,local_views(U),local_views(fv),dv)
```
are useful, it would be ideal to then retrieve them over the whole mesh. E.g., `fv` is `PVector`, is there an operation to retrieve a `Vector` with entries defined over the whole mesh instead of distributed parts (as in Gridap.jl)?

-----
You're right, in future, I'll post on there :).

**Comment by JordiManyer** [comment]
Hi @zjwegert , 

I would advise against that for anything that needs to be performant since that involves communicating everything to every processor. But yes, you can... 
PartitionedArrays.jl has something called a `GlobalView` which is exactly what you describe. For vectors, you can call it like [this](https://github.com/fverdugo/PartitionedArrays.jl/blob/5e007745188bf4c5e23898cd94f63ba24916a74a/src/Interfaces.jl#L2154). I can't really advise you on how to procede from here, since it's not something I normally use (you should really avoid it for performance), but it should behave as a global vector. 

Note the link points to PartitionedArrays v0.2.15, which is what GridapDistributed is using. There has since been a breaking release v0.3.0, which GridapDistributed does not support yet (so that you do not get confusing while going through the code).

**Comment by zjwegert** [comment]
Great, that helps a lot! I'll have to have a think about whether it is worth simply re-writing my code-base with this all in mind.

Thanks for the help and fast responses!
Zach
