### ISSUE TITLE
Implement localize function to remove ghost cells of a given triangulation

### ISSUE THREAD

**Issue by fverdugo** [gridap/GridapDistributed.jl#2]

**Comment by fverdugo** [comment]
``` julia
trian_l = localize(trian_lg,part,cell_to_owner)
```
Compute a new triangulation `trian_l` that points only to locally owned cells, i.e.
```julia
all( cell_to_owner[ get_cell_id(trian_l) ] .== part ) #-> true 
```
from a given triangulation that (possibly) points to both  owned and ghost cells.

It should be easy to implement using `RestrictedTriangulation`

**Comment by fverdugo** [comment]
Added function `remove_ghost_cells` and `include_ghost_cells` in commit 1be9a853896049199019bca3ac45dd427b2e5e65

Addresses first item in issue #3

**Comment by fverdugo** [comment]
Functions `remove_ghost_cells` and `include_ghost_cells` still need to be extended to boundary and skeleton triangulations.

**Comment by amartinhuertas** [comment]
> Functions remove_ghost_cells and include_ghost_cells still need to be extended to boundary and skeleton triangulations.

Done [here](https://github.com/gridap/GridapDistributed.jl/blob/implement_owned_cells_strategy/src/DistributedTriangulations.jl#L14) for `SkeletonTriangulation`. For `BoundaryTriangulation` the `include_ghost_cells` for regular triangulations can be re-used as is.

However, in order to have fully working `TriangulationPortion` of `BoundaryTriangulation` and `SkeletonTriangulation` this [PR](https://github.com/gridap/Gridap.jl/pull/267) is needed in `Gridap.jl`.
