### ISSUE TITLE
The "Simple" example does not run on a serial machine

### ISSUE THREAD

**Issue by PetrKryslUCSD** [gridap/GridapDistributed.jl#83]
I am testing this on a tablet which I use to play with software.
The example from the README that starts on line 26 does not run.
The
`ERROR: Number of MPI processors must be equivalent to number of parts.`
is probably coming from MPI, but still, this being the "simple" example,
there should be some way of making it run even if someone does not have 
a parallel machine access.

**Comment by amartinhuertas** [comment]
Hi @PetrKryslUCSD, 

`GridapDistributed.jl` scripts can be either run in "sequential" or MPI-parallel mode. 

You should be able to run in both modes, even if you do no have access to a parallel machine. In the former mode, you just replace `mpi` by `sequential` in the `prun` call, and execute the julia script as any other julia sequential script.

The instructions for executing a script that follows MPI-parallel mode of execution (like the one in the Simple example section) are available in the README section https://github.com/gridap/GridapDistributed.jl#mpi-parallel-julia-script-execution-instructions right below the example. The error you are getting is because you should execute the script with `mpiexecjl` with as many MPI processes as the number of parts (`4` in the case of the example). We decided to put the example in the MPI-parallel mode (instead of sequential mode) because this is the kind of execution mode which is ultimately more useful for GridapDistributed.jl users.

I will made all this more clear in the README.md of the package. 

Thanks for reporting!
@amartinhuertas

**Comment by amartinhuertas** [comment]
solved in https://github.com/gridap/GridapDistributed.jl/commit/a264a26a52aeddb559b8c593aeef124374c3b14c
